name: CI

on: [push]

jobs:
  test:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"  # respect [ci skip] commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install coveralls pydot graphviz pytest pytest-cov galpy
          python setup.py install
      - name: Test mw-plot
        if: ${{ matrix.PAPER_MODELS == false}}
        run: >
          python -m pytest --cov mw_plot --cov-report=xml tests/test_mwplot.py