name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install coveralls pydot graphviz pytest pytest-cov galpy astroquery numpy bokeh
          pip install .
      - name: Test mw-plot
        run: >
          python -m pytest --cov mw_plot --cov-report=xml tests/test_mwplot.py
