name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install coveralls pytest pytest-cov galpy astroquery numpy bokeh
          pip install .
      - name: Test mw-plot
        run: >
          python -m pytest -v tests/ --cov=mw_plot --cov-report=xml