# Deploy wheels and sdist to PyPI (upon release creation)
name: Deploy release

on:   
  release:
      types: [created]

jobs:
  build_sdist:
    name: Run sdist
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest
    steps:
      # check-out this repository
      - uses: actions/checkout@v4
      # Setup python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install galpy astroquery numpy build
      - name: Build sdist
        run: |
          python -m build --sdist
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
